function writeFurutaActorHeader(weights, outputHeader)
%WRITEFURUTAACTORHEADER Write C++ header with actor weights.

outputHeader = string(outputHeader);
outDir = fileparts(outputHeader);
if strlength(outDir) > 0 && ~isfolder(outDir)
    mkdir(outDir);
end

fid = fopen(outputHeader, "w");
if fid < 0
    error("writeFurutaActorHeader:OpenFailed", ...
        "Could not open output header: %s", outputHeader);
end
cleanupObj = onCleanup(@() fclose(fid));

fprintf(fid, "#pragma once\n\n");
fprintf(fid, "// Generated by writeFurutaActorHeader.m\n");
fprintf(fid, "// Source: %s\n", string(weights.SourceAgentFile));
fprintf(fid, "// Generated at: %s\n\n", string(weights.GeneratedAt));
fprintf(fid, "#include <cstdint>\n\n");
fprintf(fid, "namespace rl_policy_weights {\n\n");
fprintf(fid, "constexpr int INPUT_SIZE = %d;\n", weights.InputSize);
fprintf(fid, "constexpr int HIDDEN1_SIZE = %d;\n", weights.Hidden1Size);
fprintf(fid, "constexpr int HIDDEN2_SIZE = %d;\n", weights.Hidden2Size);
fprintf(fid, "constexpr int OUTPUT_SIZE = %d;\n", weights.OutputSize);
fprintf(fid, "constexpr float ACTION_CURRENT_SCALE_A = %sf;\n", localFloatLiteral(weights.ActionScale));
fprintf(fid, "constexpr float POLICY_SAMPLE_TIME_S = %sf;\n\n", localFloatLiteral(weights.SampleTime));

localWriteMatrix(fid, "W1", weights.W1);
localWriteVector(fid, "b1", weights.b1);
localWriteMatrix(fid, "W2", weights.W2);
localWriteVector(fid, "b2", weights.b2);
localWriteMatrix(fid, "W3", weights.W3);
localWriteVector(fid, "b3", weights.b3);

fprintf(fid, "} // namespace rl_policy_weights\n");
end

function localWriteMatrix(fid, name, value)
[rows, cols] = size(value);
fprintf(fid, "static constexpr float %s[%d][%d] = {\n", name, rows, cols);
for r = 1:rows
    fprintf(fid, "    {");
    for c = 1:cols
        fprintf(fid, "%sf", localFloatLiteral(value(r, c)));
        if c < cols
            fprintf(fid, ", ");
        end
    end
    if r < rows
        fprintf(fid, "},\n");
    else
        fprintf(fid, "}\n");
    end
end
fprintf(fid, "};\n\n");
end

function localWriteVector(fid, name, value)
value = value(:);
fprintf(fid, "static constexpr float %s[%d] = {", name, numel(value));
for k = 1:numel(value)
    fprintf(fid, "%sf", localFloatLiteral(value(k)));
    if k < numel(value)
        fprintf(fid, ", ");
    end
end
fprintf(fid, "};\n\n");
end

function txt = localFloatLiteral(value)
txt = sprintf("%.9g", value);
if ~contains(txt, ".") && ~contains(lower(txt), "e")
    txt = txt + ".0";
end
end
