%% Rerun the four closed-loop hardware-vs-simulation swing-up comparisons

scriptDir = fileparts(mfilename("fullpath"));
repoRoot = fileparts(fileparts(scriptDir));
addpath(scriptDir)

cases = [
    struct( ...
        "HardwareRoot", fullfile(repoRoot, "results", "model_vs_hardware", ...
            "swingup_500hz_long_hardware_scale0p4_lim4a_20260707"), ...
        "SimFile", fullfile(repoRoot, "results", "model_vs_hardware", ...
            "swingup_500hz_long_sim_simple_closed_loop_scale0p4_lim4a_20260707", ...
            "20260707_202741_simple_closed_loop", "run.mat"), ...
        "Label", "hardware scale0p4 lim4a vs simple sim closed loop")
    struct( ...
        "HardwareRoot", fullfile(repoRoot, "results", "model_vs_hardware", ...
            "swingup_500hz_long_hardware_scale1p0_lim4a_20260707"), ...
        "SimFile", fullfile(repoRoot, "results", "model_vs_hardware", ...
            "swingup_500hz_long_sim_simple_closed_loop_scale1p0_lim4a_20260707", ...
            "20260707_204008_simple_closed_loop", "run.mat"), ...
        "Label", "hardware scale1p0 lim4a vs simple sim closed loop")
    struct( ...
        "HardwareRoot", fullfile(repoRoot, "results", "model_vs_hardware", ...
            "swingup_500hz_long_hardware_scale1p0_lim4a_20260707"), ...
        "SimFile", fullfile(repoRoot, "results", "model_vs_hardware", ...
            "swingup_500hz_long_sim_detailed_closed_loop_scale1p0_lim4a_20260707", ...
            "20260707_205146_detailed_closed_loop", "run.mat"), ...
        "Label", "hardware scale1p0 lim4a vs detailed sim closed loop")
    struct( ...
        "HardwareRoot", fullfile(repoRoot, "results", "model_vs_hardware", ...
            "swingup_500hz_long_hardware_scale0p4_lim4a_20260707"), ...
        "SimFile", fullfile(repoRoot, "results", "model_vs_hardware", ...
            "swingup_500hz_long_sim_detailed_closed_loop_scale0p4_lim4a_20260707", ...
            "20260707_205733_detailed_closed_loop", "run.mat"), ...
        "Label", "hardware scale0p4 lim4a vs detailed sim closed loop")
];

comparisonAnalysis = repmat(struct(), numel(cases), 1);

for idx = 1:numel(cases)
    D = dir(fullfile(cases(idx).HardwareRoot, "*", "run.mat"));
    hardwareFiles = fullfile(string({D.folder}), string({D.name})).';

    if isempty(hardwareFiles)
        error("No hardware run files found under: %s", cases(idx).HardwareRoot);
    end

    if ~isfile(cases(idx).SimFile)
        error("Simulation run file not found: %s", cases(idx).SimFile);
    end

    runFiles = [
        hardwareFiles
        string(cases(idx).SimFile)
    ];

    fprintf("Running comparison %d/%d: %s\n", ...
        idx, numel(cases), cases(idx).Label);

    comparisonAnalysis(idx).Label = cases(idx).Label;
    comparisonAnalysis(idx).HardwareRoot = cases(idx).HardwareRoot;
    comparisonAnalysis(idx).SimFile = cases(idx).SimFile;
    comparisonAnalysis(idx).Analysis = plotFurutaSwingupHardwareRuns(runFiles, ...
        Label=cases(idx).Label, ...
        AverageRunIndices=1:numel(hardwareFiles), ...
        SaveOutput=true);

    close(comparisonAnalysis(idx).Analysis.overlayFigure);
    close(comparisonAnalysis(idx).Analysis.averageFigure);
end
