function saved = saveCurrentWorkspaceSwingupSimulationRun(simout1, options)
%SAVECURRENTWORKSPACESWINGUPSIMULATIONRUN Save one simulated swing-up run.
%
% Examples:
%   saved = saveCurrentWorkspaceSwingupSimulationRun(simout1, ...
%       ModelVariant="simple", ActionScale=0.4, CurrentLimitAbs=4.0);
%
%   saved = saveCurrentWorkspaceSwingupSimulationRun(simout1, ...
%       ModelVariant="detailed", Mode="input_replay", ...
%       ActionScale=1.0, CurrentLimitAbs=0.5);

arguments
    simout1
    options.Agent (1,1) string = "TD3 500Hz long"
    options.ModelVariant (1,1) string {mustBeMember(options.ModelVariant, ...
        ["simple", "detailed", "analytical", "simscape", "other"])} = "other"
    options.Mode (1,1) string {mustBeMember(options.Mode, ...
        ["closed_loop", "input_replay"])} = "closed_loop"
    options.ActionScale (1,1) double = NaN
    options.CurrentLimitAbs (1,1) double = NaN
    options.TestDate (1,1) string = string(datetime("today", "Format", "yyyyMMdd"))
    options.TestName (1,1) string = ""
    options.RunLabel (1,1) string = ""
    options.Description (1,1) string = ""
    options.ModelDescription (1,1) string = ""
    options.InputDescription (1,1) string = ""
    options.OutputRoot (1,1) string = ""
end

scriptDir = fileparts(mfilename("fullpath"));
addpath(scriptDir);

signals = extractFurutaModelVsHardwareSignals(simout1, ...
    SourceLabel="simulation_swingup_500hz_long");

enableMask = signals.enable > 0.5;
idxEnableOn = find(enableMask, 1, "first");

enableOnTime = NaN;
enableOffTime = NaN;
enabledDuration = NaN;

if ~isempty(idxEnableOn)
    enableOnTime = signals.t(idxEnableOn);
    idxEnableOff = find(~enableMask & signals.t > enableOnTime, 1, "first");
    if ~isempty(idxEnableOff)
        enableOffTime = signals.t(idxEnableOff);
    end
    enabledDuration = signals.t(find(enableMask, 1, "last")) - enableOnTime;
end

if strlength(options.TestName) == 0
    testName = localDefaultTestName(options);
else
    testName = options.TestName;
end

if strlength(options.RunLabel) == 0
    runLabel = options.ModelVariant + "_" + options.Mode;
else
    runLabel = options.RunLabel;
end

if strlength(options.Description) == 0
    description = "Simulated swing-up using TD3 500Hz long agent.";
else
    description = options.Description;
end

if strlength(options.ModelDescription) == 0
    modelDescription = options.ModelVariant + " model, " + options.Mode;
else
    modelDescription = options.ModelDescription;
end

if strlength(options.InputDescription) == 0
    if options.Mode == "closed_loop"
        inputDescription = "Closed-loop RL current command generated by simulation.";
    else
        inputDescription = "Simulation driven by replayed input signals.";
    end
else
    inputDescription = options.InputDescription;
end

saveOptions = { ...
    'TestName', testName, ...
    'SourceType', "simulation", ...
    'Description', description, ...
    'ModelDescription', modelDescription, ...
    'InputDescription', inputDescription, ...
    'Duration', signals.t(end) - signals.t(1), ...
    'RunLabel', runLabel};

if strlength(options.OutputRoot) > 0
    saveOptions = [saveOptions, {'OutputRoot', options.OutputRoot}];
end

saved = saveFurutaModelVsHardwareRun(simout1, saveOptions{:});

enabledSignals = localEnabledSignals(signals, enableMask, enableOnTime);

swingupInfo = struct();
swingupInfo.Agent = options.Agent;
swingupInfo.ModelVariant = options.ModelVariant;
swingupInfo.Mode = options.Mode;
swingupInfo.ActionScale = options.ActionScale;
swingupInfo.CurrentLimitAbs = options.CurrentLimitAbs;
swingupInfo.EnableOnTime = enableOnTime;
swingupInfo.EnableOffTime = enableOffTime;
swingupInfo.EnabledDuration = enabledDuration;
swingupInfo.EnabledSampleCount = nnz(enableMask);
swingupInfo.Note = "enabledSignals is time-shifted so t=0 is first enable sample.";

save(saved.matPath, "enabledSignals", "swingupInfo", "-append");

saved.enabledSignals = enabledSignals;
saved.swingupInfo = swingupInfo;

fprintf("Saved simulated swing-up run:\n  %s\n", saved.runDir);
fprintf("Enable ON:  %.3f s\n", enableOnTime);
fprintf("Enable OFF: %.3f s\n", enableOffTime);
end

function testName = localDefaultTestName(options)
testName = "swingup_500hz_long_sim_" + options.ModelVariant + "_" + options.Mode;

if isfinite(options.ActionScale)
    testName = testName + "_scale" + localActionScaleSlug(options.ActionScale);
end

if isfinite(options.CurrentLimitAbs)
    testName = testName + "_lim" + localNumberSlug(options.CurrentLimitAbs) + "a";
end

testName = testName + "_" + options.TestDate;
end

function slug = localActionScaleSlug(value)
if abs(value - round(value)) < 1e-9
    slug = regexprep(string(sprintf("%.1f", value)), "\.", "p");
else
    slug = localNumberSlug(value);
end
end

function slug = localNumberSlug(value)
slug = regexprep(string(sprintf("%.6g", value)), "\.", "p");
slug = regexprep(slug, "-", "m");
end

function enabledSignals = localEnabledSignals(signals, enableMask, enableOnTime)
enabledSignals = struct();

if ~any(enableMask) || ~isfinite(enableOnTime)
    enabledSignals.t = [];
    enabledSignals.theta1 = [];
    enabledSignals.theta2 = [];
    enabledSignals.omega1 = [];
    enabledSignals.omega2 = [];
    enabledSignals.theta2_wrapped = [];
    enabledSignals.current_cmd = [];
    enabledSignals.current = [];
    enabledSignals.enable = [];
    return
end

enabledSignals.t = signals.t(enableMask) - enableOnTime;
enabledSignals.theta1 = signals.theta1(enableMask);
enabledSignals.theta2 = signals.theta2(enableMask);
enabledSignals.omega1 = signals.omega1(enableMask);
enabledSignals.omega2 = signals.omega2(enableMask);
enabledSignals.theta2_wrapped = signals.theta2_wrapped(enableMask);
enabledSignals.current_cmd = signals.current_cmd(enableMask);
enabledSignals.current = signals.current(enableMask);
enabledSignals.enable = signals.enable(enableMask);
end
