addpath("scripts/analysis")

%%
D = dir(furutaResultsPath("model_vs_hardware", ...
    "swingup_500hz_long_hardware_scale0p4_lim4a_20260707", "*", "run.mat"));

hardwareFiles = fullfile(string({D.folder}), string({D.name})).';
simFile = furutaResultsPath("model_vs_hardware", ...
    "swingup_500hz_long_sim_simple_closed_loop_scale0p4_lim4a_20260707", ...
    "20260707_202741_simple_closed_loop", "run.mat");
%%
D = dir(furutaResultsPath("model_vs_hardware", ...
    "swingup_500hz_long_hardware_scale1p0_lim4a_20260707", "*", "run.mat"));
hardwareFiles = fullfile(string({D.folder}), string({D.name})).';
simFile = furutaResultsPath("model_vs_hardware", ...
    "swingup_500hz_long_sim_simple_closed_loop_scale1p0_lim4a_20260707", ...
    "20260707_204008_simple_closed_loop", "run.mat");
%%
D = dir(furutaResultsPath("model_vs_hardware", ...
    "swingup_500hz_long_hardware_scale1p0_lim4a_20260707", "*", "run.mat"));
hardwareFiles = fullfile(string({D.folder}), string({D.name})).';
simFile = furutaResultsPath("model_vs_hardware", ...
    "swingup_500hz_long_sim_detailed_closed_loop_scale1p0_lim4a_20260707", ...
    "20260707_205146_detailed_closed_loop", "run.mat");
%%
D = dir(furutaResultsPath("model_vs_hardware", ...
    "swingup_500hz_long_hardware_scale1p0_lim4a_20260707", "*", "run.mat"));
hardwareFiles = fullfile(string({D.folder}), string({D.name})).';
simFile = furutaResultsPath("model_vs_hardware", ...
    "swingup_500hz_long_sim_detailed_closed_loop_scale1p0_lim3a_20260708", ...
    "20260708_230334_detailed_closed_loop", "run.mat");
%%
D = dir(furutaResultsPath("model_vs_hardware", ...
    "swingup_500hz_long_hardware_scale0p4_lim4a_20260707", "*", "run.mat"));
hardwareFiles = fullfile(string({D.folder}), string({D.name})).';
simFile = furutaResultsPath("model_vs_hardware", ...
    "swingup_500hz_long_sim_detailed_closed_loop_scale0p4_lim4a_20260707", ...
    "20260707_205733_detailed_closed_loop", "run.mat");
%%
runFiles = [
    hardwareFiles
    simFile
];

analysis = plotFurutaSwingupHardwareRuns(runFiles, ...
    Label="hardware scale1p0 lim3a vs detailed sim (v1) closed loop", ...
    AverageRunIndices=1:numel(hardwareFiles), ...
    SaveOutput=true);
