addpath("scripts")
runDir = furutaResultsPath("TD3", ...
    "run_20260616_233822_td3_mathworks_style_voltage");

finalizeFurutaDirectTD3Run(runDir, ...
    RunShortEvaluation=true, ...
    RunFullEvaluation=true, ...
    EvaluationModelName="inv_rot_pen_RL_cntr_simscape_sim_2_analytical_active", ...
    EvaluationOutputDir=fullfile(runDir,"analysis","voltage_analytical_active_2"), ...
    SaveFinalMat=false);
