%%
addpath(genpath("scripts"))
%%
loaded = loadFurutaFinalAgent(furutaResultsPath("TD3", ...
    "run_20260616_012625_td3_mathworks_style_wide"), ...
    OpenModel=true);

%%
loaded = loadFurutaFinalAgent(furutaResultsPath("TD3", ...
    "run_20260616_233822_td3_mathworks_style_voltage"), ...
    OpenModel=true);
%%
loaded = loadFurutaFinalAgent(furutaResultsPath("TD3", ...
    "run_20260618_121014_td3_mathworks_style_pi_current_1b_500hz"), ...
    OpenModel=true);
%%
bdclose all
clearvars

loaded = loadFurutaFinalAgent(furutaResultsPath("TD3", ...
    "run_20260618_121014_td3_mathworks_style_pi_current_1b_500hz"), ...
    OpenModel=true, ...
    InitialTheta=[0; 0], ...
    InitialOmega=[0; 0]);

%%
bdclose all
clearvars
%%
loaded = loadFurutaFinalAgent(furutaResultsPath("TD3", ...
    "run_20260618_223832_td3_mathworks_style_pi_current_1b_500hz_long"), ...
    OpenModel=false, ...
    InitialTheta=[0; 0], ...
    InitialOmega=[0; 0]);

%%
loaded = loadFurutaFinalAgent(furutaResultsPath("TD3", ...
    "run_20260629_130518_td3_mathworks_style_pi_current_1b_500hz_long_actor1x64_critic2x64"), ...
    OpenModel=true, ...
    InitialTheta=[0; 0], ...
    InitialOmega=[0; 0]);
%%
loaded = loadFurutaFinalAgent(furutaResultsPath("TD3", ...
    "run_20260704_015559_td3_mathworks_style_pi_current_1c_500hz_long_detailed"), ...
    OpenModel=false, ...
    InitialTheta=[0; 0], ...
    InitialOmega=[0; 0]);
%%
loaded = loadFurutaFinalAgent(furutaResultsPath("TD3", ...
    "run_20260703_230817_td3_mathworks_style_pi_current_1c_500hz_long_detailed"), ...
    OpenModel=false, ...
    InitialTheta=[0; 0], ...
    InitialOmega=[0; 0]);
%%
loaded = loadFurutaFinalAgent(furutaResultsPath("TD3", ...
    "run_20260705_221352_td3_mathworks_style_pi_current_1c_500hz_long_detailed_near_upright"), ...
    OpenModel=false, ...
    InitialTheta=[0; 0], ...
    InitialOmega=[0; 0]);
%%
loaded = loadFurutaFinalAgent(furutaResultsPath("TD3", ...
    "run_20260706_102951_td3_mathworks_style_pi_current_1d_500hz_near_upright_imeas_scratch"), ...
    OpenModel=true, ...
    InitialTheta=[0; 0], ...
    InitialOmega=[0; 0]);
%%
loaded = loadFurutaFinalAgent(furutaResultsPath("TD3", ...
    "run_20260708_151229_td3_mathworks_style_pi_current_1b_500hz_theta1_offset_scratch_current_1p5"), ...
    OpenModel=true, ...
    InitialTheta=[0; pi], ...
    InitialOmega=[0; 0]);
%%
loaded = loadFurutaFinalAgent(furutaResultsPath("TD3", ...
    "run_20260708_143303_td3_mathworks_style_pi_current_1c_500hz_theta1_offset_scratch"), ...
    OpenModel=true, ...
    InitialTheta=[0; pi], ...
    InitialOmega=[0; 0]);
%%
loaded = loadFurutaFinalAgent(furutaResultsPath("TD3", ...
    "run_20260708_222715_td3_mathworks_style_pi_current_1c_500hz_long_detailed_scratch7000"), ...
    OpenModel=true, ...
    InitialTheta=[0; pi], ...
    InitialOmega=[0; 0]);
%%
omega0 = [10; 10];
%%
omega0 = [0; 0];
%%
theta0 = [0; 0];
%%
theta0 = [0; pi];
%%
theta0 = [0; pi+deg2rad(10)];

%%
addpath(genpath(fullfile("uC", "nucleo_policy_deploy", "matlab")))
%%
export = exportFurutaActorForNucleo(finalAgentFile, ...
    OutputHeader=fullfile("uC", "nucleo_policy_deploy", "lib", ...
        "RLPolicy", "rl_policy_weights.h"), ...
    OutputMat=fullfile(runDir, "actor_export_nucleo.mat"));
%%
runDir = furutaResultsPath("TD3", ...
    "run_20260618_223832_td3_mathworks_style_pi_current_1b_500hz_long");
S = load(fullfile(runDir, "actor_export_nucleo.mat"), "weights");
ucPolicyWeights = S.weights;

%%
addpath(genpath("uC/nucleo_policy_deploy/matlab"))
loadFurutaUcPolicyMirrorParams

%%
1/Ts
