addpath(genpath("scripts"));

[inside, info] = isInLqrCaptureRegion( ...
    theta1, theta2, omega1, omega2, ...
    CurrentLimit=1.5, ...
    Rho=0.08, ...
    Theta1Guard=deg2rad(25), ...
    Theta2Guard=deg2rad(24), ...
    Omega1Guard=5, ...
    Omega2Guard=6);

%%
[inside, info] = isInLqrCaptureRegion( ...
    deg2rad(1), deg2rad(10), 1, 1, ...
    CurrentLimit=1.5, ...
    Rho=0.1, ...
    Theta2IsError=true);
inside