%%
addpath("scripts/analysis")
%%
run("scripts/analysis/inspectCurrentWorkspaceSwingupHardwareRun.m")

%%
savedSimple04 = saveCurrentWorkspaceSwingupSimulationRun(simout1, ...
    ModelVariant="simple", ...
    Mode="closed_loop", ...
    ActionScale=0.4, ...
    CurrentLimitAbs=4.0, ...
    ModelDescription="simple analytical model, closed-loop TD3 500Hz long");

%%
savedSimple10 = saveCurrentWorkspaceSwingupSimulationRun(simout1, ...
    ModelVariant="simple", Mode="closed_loop", ...
    ActionScale=1.0, CurrentLimitAbs=4);

%%
savedDetailed10 = saveCurrentWorkspaceSwingupSimulationRun(simout1, ...
    ModelVariant="detailed", Mode="closed_loop", ...
    ActionScale=1.0, CurrentLimitAbs=4);
%%
savedDetailed04 = saveCurrentWorkspaceSwingupSimulationRun(simout1, ...
    ModelVariant="detailed", Mode="closed_loop", ...
    ActionScale=0.4, CurrentLimitAbs=4);
%%
savedDetailed11 = saveCurrentWorkspaceSwingupSimulationRun(simout1, ...
    ModelVariant="detailed", Mode="closed_loop", ...
    ActionScale=1.0, CurrentLimitAbs=3);

%%
runFile = "results/model_vs_hardware/swingup_500hz_long_hardware_scale0p4_lim4a_20260707/20260707_171506_hardware_closed_loop/run.mat";

[i_cmd_hardware, info, replay] = makeFurutaHardwareReplayCurrentCommand(runFile, ...
    Duration=10.0, ...
    SignalPadMode="zero");

%%
runFile = "results/model_vs_hardware/swingup_500hz_long_hardware_scale1p0_lim4a_20260707/20260707_174246_hardware_closed_loop/run.mat";

[i_cmd_hardware, info, replay] = makeFurutaHardwareReplayCurrentCommand(runFile, ...
    Duration=10.0, ...
    SignalPadMode="zero");