function comparison = compareWetoInputRuns(runDirs, options)
%COMPAREWETOINPUTRUNS Collect compact metrics for Weto-input run comparisons.
%
%   comparison = compareWetoInputRuns(runDirs) reads evaluation summary CSVs
%   from each run folder and returns one table focused on swing-up success,
%   final upright quality, action chatter, and electrical effort.
%
%   runDirs can include folders that do not exist yet. Missing folders are
%   reported in the returned table, which makes the helper useful before a
%   run copied from another machine is available.

arguments
    runDirs (:,1) string
    options.OutputCsv (1,1) string = fullfile("results", "weto_input_comparison_summary.csv")
    options.IncludeMissing (1,1) logical = true
end

rows = table();

for idx = 1:numel(runDirs)
    runDir = string(runDirs(idx));
    runRows = summarizeRun(runDir, options.IncludeMissing);
    rows = [rows; runRows]; %#ok<AGROW>
end

comparison = rows;

if strlength(options.OutputCsv) > 0
    outDir = string(fileparts(options.OutputCsv));
    if strlength(outDir) > 0 && ~isfolder(outDir)
        mkdir(outDir);
    end
    writetable(comparison, options.OutputCsv);
    fprintf("Saved Weto-input comparison summary:\n  %s\n", options.OutputCsv);
end
end

function rows = summarizeRun(runDir, includeMissing)
[~, runName] = fileparts(runDir);

if ~isfolder(runDir)
    if includeMissing
        rows = missingRunRow(runDir, runName, "run folder missing");
    else
        rows = table();
    end
    return;
end

summaryFiles = dir(fullfile(runDir, "evaluation", "*_summary.csv"));
if isempty(summaryFiles)
    if includeMissing
        rows = missingRunRow(runDir, runName, "no evaluation summary CSVs");
    else
        rows = table();
    end
    return;
end

rows = table();
for idx = 1:numel(summaryFiles)
    summaryPath = fullfile(summaryFiles(idx).folder, summaryFiles(idx).name);
    T = readtable(summaryPath);
    if isempty(T)
        row = missingRunRow(runDir, runName, "empty summary: " + string(summaryFiles(idx).name));
    else
        row = summarizeSummaryTable(runDir, runName, summaryPath, T);
    end
    rows = [rows; row]; %#ok<AGROW>
end
end

function row = summarizeSummaryTable(runDir, runName, summaryPath, T)
evalSetName = getStringValue(T, "EvalSetName", erase(string(getFileBase(summaryPath)), "_summary"));

row = table( ...
    string(runName), ...
    string(runDir), ...
    string(evalSetName), ...
    string(summaryPath), ...
    true, ...
    "", ...
    getNumericValue(T, "NumCases"), ...
    getNumericValue(T, "FailureRate"), ...
    getNumericValue(T, "MeanFinalTheta2MAE"), ...
    getNumericValue(T, "MaxFinalTheta2Error"), ...
    getNumericValue(T, "MeanTheta2IAE"), ...
    getNumericValue(T, "MeanTheta2EndRMS"), ...
    getNumericValue(T, "MeanTheta2EndOscRMS"), ...
    getNumericValue(T, "MeanTheta2EndPeakToPeak"), ...
    getNumericValue(T, "MeanTheta2EndOscFreqHz"), ...
    getNumericValue(T, "MeanActionDiffRMS"), ...
    getNumericValue(T, "MeanActionEndOscRMS"), ...
    getNumericValue(T, "MeanActionEndPeakToPeak"), ...
    getNumericValue(T, "MeanActionEndOscFreqHz"), ...
    getNumericValue(T, "MeanElectricalAbsEnergy"), ...
    getNumericValue(T, "MeanAbsElectricalPower"), ...
    getNumericValue(T, "MeanDActionEnergy"), ...
    getNumericValue(T, "Score"), ...
    VariableNames=columnNames());
end

function row = missingRunRow(runDir, runName, message)
nanValue = NaN;
row = table( ...
    string(runName), ...
    string(runDir), ...
    "", ...
    "", ...
    false, ...
    string(message), ...
    nanValue, nanValue, nanValue, nanValue, nanValue, ...
    nanValue, nanValue, nanValue, nanValue, nanValue, ...
    nanValue, nanValue, nanValue, nanValue, nanValue, ...
    nanValue, nanValue, ...
    VariableNames=columnNames());
end

function names = columnNames()
names = [ ...
    "RunName", ...
    "RunDir", ...
    "EvalSetName", ...
    "SummaryCsv", ...
    "Available", ...
    "Message", ...
    "NumCases", ...
    "FailureRate", ...
    "MeanFinalTheta2MAE", ...
    "MaxFinalTheta2Error", ...
    "MeanTheta2IAE", ...
    "MeanTheta2EndRMS", ...
    "MeanTheta2EndOscRMS", ...
    "MeanTheta2EndPeakToPeak", ...
    "MeanTheta2EndOscFreqHz", ...
    "MeanActionDiffRMS", ...
    "MeanActionEndOscRMS", ...
    "MeanActionEndPeakToPeak", ...
    "MeanActionEndOscFreqHz", ...
    "MeanElectricalAbsEnergy", ...
    "MeanAbsElectricalPower", ...
    "MeanDActionEnergy", ...
    "Score"];
end

function value = getNumericValue(T, name)
if ~ismember(name, T.Properties.VariableNames)
    value = NaN;
    return;
end

x = T.(name);
if isempty(x)
    value = NaN;
elseif isnumeric(x) || islogical(x)
    value = double(x(1));
else
    value = str2double(string(x(1)));
end
end

function value = getStringValue(T, name, fallback)
if ~ismember(name, T.Properties.VariableNames)
    value = string(fallback);
    return;
end

x = T.(name);
if isempty(x)
    value = string(fallback);
else
    value = string(x(1));
end
end

function base = getFileBase(path)
[~, base] = fileparts(path);
base = string(base);
end
