%TRAINFURUTAMATLABSWINGUPODE3STUDENT32TD3 Train 1x32 actor and 2x32 critics.

scriptDir = fileparts(mfilename("fullpath"));
repoRoot = fileparts(scriptDir);
cd(repoRoot)
addpath(genpath(fullfile(repoRoot, "scripts")))
rng(0, "twister")

cfg = makeFurutaMatlabSwingupOde3Student32TD3Config();
env = createFurutaAnalyticalSwingupEnvSimulinkConvention(cfg);
obsInfo = getObservationInfo(env);
actInfo = getActionInfo(env);
agent = createTD3AgentFuruta(obsInfo, actInfo, cfg.Agent);

if ~isfolder(cfg.Training.OutputRoot)
    mkdir(cfg.Training.OutputRoot);
end
if ~isfolder(cfg.Training.ConfigDir)
    mkdir(cfg.Training.ConfigDir);
end
if ~isfolder(cfg.Training.SavedAgentDir)
    mkdir(cfg.Training.SavedAgentDir);
end

fprintf("From-scratch 32-neuron student TD3 training\n");
fprintf("Actor 1x32, critics 2x32, batch %d, max %d updates/episode.\n", ...
    cfg.Agent.MiniBatchSize, ...
    cfg.Agent.NumEpoch * cfg.Agent.MaxMiniBatchPerEpoch);
fprintf("Up to %d episodes of %.1f s; CPU; parallel disabled.\n", ...
    cfg.Training.MaxEpisodes, cfg.Training.EpisodeDuration);
fprintf("Stop requires %d consecutive fixed evaluations with 10/10 captures.\n", ...
    cfg.Evaluation.RequiredConsecutivePerfect);

trainOpts = rlTrainingOptions( ...
    MaxEpisodes=cfg.Training.MaxEpisodes, ...
    MaxStepsPerEpisode=cfg.Done.MaxSteps, ...
    Verbose=cfg.Training.Verbose, ...
    Plots=cfg.Training.PlotMode, ...
    ScoreAveragingWindowLength=cfg.Training.ScoreAveragingWindowLength, ...
    StopTrainingCriteria=cfg.Training.StopTrainingCriteria, ...
    StopTrainingValue=cfg.Training.StopTrainingValue, ...
    SaveAgentCriteria=cfg.Training.SaveAgentCriteria, ...
    SaveAgentValue=cfg.Training.SaveAgentValue, ...
    SaveAgentDirectory=cfg.Training.SavedAgentDir, ...
    UseParallel=false);

% IMPORTANT: Keep parallel training disabled. The custom evaluator has
% previously failed or crashed when combined with parallel RL training.
evaluator = rlCustomEvaluator( ...
    @(evaluationAgent, evaluationEnv, trainingInfo) ...
        evaluateFurutaFixedSwingupCasesDuringTraining( ...
            evaluationAgent, evaluationEnv, trainingInfo, cfg), ...
    EvaluationFrequency=cfg.Evaluation.CustomEvaluationFrequency);

trainingStats = train(agent, env, trainOpts, Evaluator=evaluator);
save(fullfile(cfg.Training.OutputRoot, cfg.Training.FinalSaveName), ...
    "agent", "trainingStats", "cfg");
