%TRAINFURUTAMATLABSWINGUPODE3STUDENT16TD3 Train 1x16 actor and 2x16 critics.
%
% This run has its own output directory and can execute in a second MATLAB
% process alongside the 32-neuron experiment. UseParallel remains false
% inside each training process because the custom evaluator is enabled.

scriptDir = fileparts(mfilename("fullpath"));
repoRoot = fileparts(scriptDir);
cd(repoRoot)
addpath(genpath(fullfile(repoRoot, "scripts")))
rng(1, "twister")

cfg = makeFurutaMatlabSwingupOde3Student16TD3Config();
env = createFurutaAnalyticalSwingupEnvSimulinkConvention(cfg);
obsInfo = getObservationInfo(env);
actInfo = getActionInfo(env);
agent = createTD3AgentFuruta(obsInfo, actInfo, cfg.Agent);

if ~isfolder(cfg.Training.OutputRoot)
    mkdir(cfg.Training.OutputRoot);
end
if ~isfolder(cfg.Training.ConfigDir)
    mkdir(cfg.Training.ConfigDir);
end
if ~isfolder(cfg.Training.SavedAgentDir)
    mkdir(cfg.Training.SavedAgentDir);
end

fprintf("From-scratch 16-neuron student TD3 training\n");
fprintf("Actor 1x16, critics 2x16, batch %d, max %d updates/episode.\n", ...
    cfg.Agent.MiniBatchSize, ...
    cfg.Agent.NumEpoch * cfg.Agent.MaxMiniBatchPerEpoch);
fprintf("Up to %d episodes of %.1f s; CPU; parallel disabled per process.\n", ...
    cfg.Training.MaxEpisodes, cfg.Training.EpisodeDuration);
fprintf("Output: %s\n", cfg.Training.OutputRoot);
fprintf("Stop requires %d consecutive fixed evaluations with 10/10 captures.\n", ...
    cfg.Evaluation.RequiredConsecutivePerfect);

trainOpts = rlTrainingOptions( ...
    MaxEpisodes=cfg.Training.MaxEpisodes, ...
    MaxStepsPerEpisode=cfg.Done.MaxSteps, ...
    Verbose=cfg.Training.Verbose, ...
    Plots=cfg.Training.PlotMode, ...
    ScoreAveragingWindowLength=cfg.Training.ScoreAveragingWindowLength, ...
    StopTrainingCriteria=cfg.Training.StopTrainingCriteria, ...
    StopTrainingValue=cfg.Training.StopTrainingValue, ...
    SaveAgentCriteria=cfg.Training.SaveAgentCriteria, ...
    SaveAgentValue=cfg.Training.SaveAgentValue, ...
    SaveAgentDirectory=cfg.Training.SavedAgentDir, ...
    UseParallel=false);

% IMPORTANT: Keep parallel training disabled within this MATLAB process.
% The two experiments are parallel only because they run in separate MATLAB
% windows. This preserves compatibility with the custom fixed-case evaluator.
evaluator = rlCustomEvaluator( ...
    @(evaluationAgent, evaluationEnv, trainingInfo) ...
        evaluateFurutaFixedSwingupCasesDuringTraining( ...
            evaluationAgent, evaluationEnv, trainingInfo, cfg), ...
    EvaluationFrequency=cfg.Evaluation.CustomEvaluationFrequency);

trainingStats = train(agent, env, trainOpts, Evaluator=evaluator);
save(fullfile(cfg.Training.OutputRoot, cfg.Training.FinalSaveName), ...
    "agent", "trainingStats", "cfg");
