%TRAINFURUTAMATLABSWINGUPODE3STUDENTTD3 From-scratch laptop training run.

scriptDir = fileparts(mfilename("fullpath"));
repoRoot = fileparts(scriptDir);
cd(repoRoot)
addpath(genpath(fullfile(repoRoot, "scripts")))
rng(0, "twister")

cfg = makeFurutaMatlabSwingupOde3StudentTD3Config();
env = createFurutaAnalyticalSwingupEnvSimulinkConvention(cfg);
obsInfo = getObservationInfo(env);
actInfo = getActionInfo(env);
agent = createTD3AgentFuruta(obsInfo, actInfo, cfg.Agent);

if ~isfolder(cfg.Training.OutputRoot)
    mkdir(cfg.Training.OutputRoot);
end
if ~isfolder(cfg.Training.ConfigDir)
    mkdir(cfg.Training.ConfigDir);
end
if ~isfolder(cfg.Training.SavedAgentDir)
    mkdir(cfg.Training.SavedAgentDir);
end

fprintf("Student TD3 training from scratch\n");
fprintf("Actor 1x64, critics 2x64, batch %d, max %d updates/episode.\n", ...
    cfg.Agent.MiniBatchSize, ...
    cfg.Agent.NumEpoch * cfg.Agent.MaxMiniBatchPerEpoch);
fprintf("Agent %.0f Hz, ode3 plant %.0f Hz, episode %.1f s, CPU, no parallel.\n", ...
    1 / cfg.Agent.SampleTime, ...
    1 / cfg.MatlabEnvironment.IntegrationStep, ...
    cfg.Training.EpisodeDuration);
fprintf("Terminal rewards: capture +%.0f, safety -%.0f, timeout -%.0f.\n", ...
    cfg.Reward.CaptureBonus, cfg.Reward.UnsafePenalty, ...
    cfg.Reward.TimeoutPenalty);

trainOpts = rlTrainingOptions( ...
    MaxEpisodes=cfg.Training.MaxEpisodes, ...
    MaxStepsPerEpisode=cfg.Done.MaxSteps, ...
    Verbose=cfg.Training.Verbose, ...
    Plots=cfg.Training.PlotMode, ...
    ScoreAveragingWindowLength=cfg.Training.ScoreAveragingWindowLength, ...
    StopTrainingCriteria=cfg.Training.StopTrainingCriteria, ...
    StopTrainingValue=cfg.Training.StopTrainingValue, ...
    SaveAgentCriteria=cfg.Training.SaveAgentCriteria, ...
    SaveAgentValue=cfg.Training.SaveAgentValue, ...
    SaveAgentDirectory=cfg.Training.SavedAgentDir, ...
    UseParallel=false);

% IMPORTANT: Keep parallel training disabled. The fixed-case custom
% evaluator has previously failed or crashed training when combined with
% UseParallel=true, and this analytical environment is not the bottleneck.
evaluator = rlCustomEvaluator( ...
    @(evaluationAgent, evaluationEnv, trainingInfo) ...
        evaluateFurutaFixedSwingupCasesDuringTraining( ...
            evaluationAgent, evaluationEnv, trainingInfo, cfg), ...
    EvaluationFrequency=cfg.Evaluation.CustomEvaluationFrequency);

trainingStats = train(agent, env, trainOpts, Evaluator=evaluator);
save(fullfile(cfg.Training.OutputRoot, cfg.Training.FinalSaveName), ...
    "agent", "trainingStats", "cfg");
