cd("C:\Users\abuj\Code\Reinforcement-Learning-Furuta-Inverted-Pendulum")
addpath(genpath("scripts"))
cfg = makeFurutaConfig();
evalCfg = makeFurutaEvalConfig(cfg);
%%
postStageEval = evaluateFurutaController( ...
    agent, env, evalCfg.PostStageCases, evalCfg, ...
    "ControllerName", "DDPG", ...
    "EvalSetName", "post_stage_test", ...
    "StageIndex", 1, ...
    "StageName", "debug");

%%
cfg = makeFurutaConfig();
evalCfg = makeFurutaEvalConfig(cfg);
tic
postStageEval = evaluateFurutaController( ...
    agent, env, evalCfg.PostStageCases, evalCfg, ...
    "ControllerName", "DDPG", ...
    "EvalSetName", "post_stage_test", ...
    "StageIndex", 1, ...
    "StageName", "debug", ...
    "RunInBackground", true, ...
    "UseFastRestart", true, ...
    "UseParallel", true, ...
    "RequestedWorkers", cfg.Training.RequestedWorkers, ...
    "AllowPoolRestart", false);
toc
%%
debugCases = evalCfg.PostStageCases(1:5, :);
postStageEval = evaluateFurutaController( ...
    agent, env, debugCases, evalCfg, ...
    "ControllerName", "DDPG", ...
    "EvalSetName", "post_stage_debug", ...
    "StageIndex", 1, ...
    "StageName", "debug", ...
    "RunInBackground", true, ...
    "UseFastRestart", true, ...
    "UseParallel", false, ...
    "RequestedWorkers", cfg.Training.RequestedWorkers, ...
    "AllowPoolRestart", false);