%EXAMPLELQRCAPTUREREGIONCHECK Example use of isInLqrCaptureRegion.
%
% Run from the repository root:
%
%   addpath(genpath("scripts"));
%   scripts/analysis/exampleLqrCaptureRegionCheck

clearvars
clc

addpath(genpath("scripts"));

rhoCapture = 0.08;
currentLimit = 1.5;

% Direction/sign convention:
%
%   theta2 = 0      pendulum hanging downward
%   theta2 = pi     pendulum upright
%
% isInLqrCaptureRegion expects measured theta2 by default and converts it to
% upright error as:
%
%   theta2_error = atan2(sin(theta2 - pi), cos(theta2 - pi))
%
% If you already have theta2_error, call the function with Theta2IsError=true.
% Positive omega2 means theta2 is increasing in the same positive direction as
% theta2_error.

% Rows: theta1 [deg], theta2 upright error [deg], omega1 [rad/s], omega2 [rad/s]
cases = [
     0,   8, 0,  0.0;   % close and still
     0,  12, 0,  0.0;   % too much angle for rho=0.08
     0,  20, 0,  0.0;   % large angle, no correcting velocity
     0,  20, 0, -2.8;   % large angle, useful incoming velocity
     0,  20, 0, -5.0;   % large angle, too much velocity
    10,  10, 0, -1.0;   % nonzero arm offset
     0, -20, 0,  2.8;   % symmetric useful incoming velocity
];

theta1 = deg2rad(cases(:, 1));
theta2Error = deg2rad(cases(:, 2));
theta2 = pi + theta2Error;
omega1 = cases(:, 3);
omega2 = cases(:, 4);

[insideStrict, infoStrict] = isInLqrCaptureRegion(theta1, theta2, omega1, omega2, ...
    CurrentLimit=currentLimit, ...
    Rho=rhoCapture, ...
    Theta1Guard=deg2rad(25), ...
    Theta2Guard=deg2rad(24), ...
    Omega1Guard=5, ...
    Omega2Guard=6);

[insideCurrentLimit, infoCurrentLimit] = isInLqrCaptureRegion(theta1, theta2, omega1, omega2, ...
    CurrentLimit=currentLimit);

T = table( ...
    cases(:, 1), ...
    cases(:, 2), ...
    omega1, ...
    omega2, ...
    infoStrict.V(:), ...
    infoStrict.ILqr(:), ...
    insideStrict(:), ...
    infoCurrentLimit.V(:), ...
    infoCurrentLimit.Rho * ones(size(theta1)), ...
    insideCurrentLimit(:), ...
    VariableNames=[ ...
        "theta1_deg", ...
        "theta2_error_deg", ...
        "omega1_rad_s", ...
        "omega2_rad_s", ...
        "V_rho_0p08", ...
        "i_lqr_A", ...
        "inside_rho_0p08", ...
        "V_current_limit", ...
        "rho_current_limit", ...
        "inside_current_limit"]);

disp(T)

fprintf("\\nStrict rho used for training/capture: %.4f\\n", rhoCapture);
fprintf("Current-limit rho for %.2f A: %.4f\\n", ...
    currentLimit, infoCurrentLimit.RhoCurrentLimit);
fprintf("\\nA state can be outside at 20 deg with zero speed, but inside at 20 deg\\n");
fprintf("when omega2 has the right sign and magnitude. That is the tilted ellipsoid.\\n");
