%TRAINFURUTAMATLABSWINGUPODE3TD3 Train with Simulink error signs and ode3.

scriptDir = fileparts(mfilename("fullpath"));
repoRoot = fileparts(fileparts(fileparts(scriptDir)));
addpath(repoRoot);
cd(repoRoot)
startupFurutaProject();
rng(0, "twister")

cfg = makeFurutaMatlabSwingupOde3TD3Config();
env = createFurutaAnalyticalSwingupEnvSimulinkConvention(cfg);
obsInfo = getObservationInfo(env);
actInfo = getActionInfo(env);
agent = createTD3AgentFuruta(obsInfo, actInfo, cfg.Agent);

if ~isfolder(cfg.Training.OutputRoot)
    mkdir(cfg.Training.OutputRoot);
end
if ~isfolder(cfg.Training.ConfigDir)
    mkdir(cfg.Training.ConfigDir);
end
if ~isfolder(cfg.Training.SavedAgentDir)
    mkdir(cfg.Training.SavedAgentDir);
end

fprintf("Training MATLAB analytical TD3 with Simulink error convention.\n");
fprintf("Agent: %.0f Hz; plant: %.0f Hz fixed-step ode3; max updates/episode: %d.\n", ...
    1 / cfg.Agent.SampleTime, ...
    1 / cfg.MatlabEnvironment.IntegrationStep, ...
    cfg.Agent.NumEpoch * cfg.Agent.MaxMiniBatchPerEpoch);

trainOpts = rlTrainingOptions( ...
    MaxEpisodes=cfg.Training.MaxEpisodes, ...
    MaxStepsPerEpisode=cfg.Done.MaxSteps, ...
    Verbose=cfg.Training.Verbose, ...
    Plots=cfg.Training.PlotMode, ...
    ScoreAveragingWindowLength=cfg.Training.ScoreAveragingWindowLength, ...
    StopTrainingCriteria=cfg.Training.StopTrainingCriteria, ...
    StopTrainingValue=cfg.Training.StopTrainingValue, ...
    SaveAgentCriteria=cfg.Training.SaveAgentCriteria, ...
    SaveAgentValue=cfg.Training.SaveAgentValue, ...
    SaveAgentDirectory=cfg.Training.SavedAgentDir, ...
    UseParallel=false);

% IMPORTANT: Keep UseParallel=false when using this custom evaluator. In
% this project, combining custom evaluation with parallel RL training has
% caused evaluator failures and training crashes. The analytical plant is
% already fast, so parallel environment workers are not useful here.
if cfg.Training.UseParallel
    error("Custom fixed-case evaluation requires Training.UseParallel=false.");
end
evaluator = rlCustomEvaluator( ...
    @(evaluationAgent, evaluationEnv, trainingInfo) ...
        evaluateFurutaFixedSwingupCasesDuringTraining( ...
            evaluationAgent, evaluationEnv, trainingInfo, cfg), ...
    EvaluationFrequency=cfg.Evaluation.CustomEvaluationFrequency);

trainingStats = train(agent, env, trainOpts, Evaluator=evaluator);
save(fullfile(cfg.Training.OutputRoot, cfg.Training.FinalSaveName), ...
    "agent", "trainingStats", "cfg");
